allowCompoundWords: true
dictionaries:
  - en_US
  - en-gb
  - git
  - markdown
  - misc
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .cspell.config.yml
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
language: en,ja
useGitignore: true
version: "0.2"
words:
  - alac
  - amebient
  - imgbotconfig
  - kito
  - kuron
  - kuroné
  - waivable
