allowCompoundWords: true
dictionaries:
  - en_US
  - en-gb
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,eo,ja
words:
  - alac
  - amebient
  - kito
  - kuron
  - kuroné
version: '0.2'
